### ISSUE TITLE
Singularity testing

### ISSUE THREAD

**Issue by rssk** [trendscenter/coinstac#1685]
## Task Description
Test

- [ ] vbm preprocesser
- [ ] vbm regression
- [ ] decentralized mancova
Data can be found in each computation repo

**Comment by dylanmartin** [comment]
VBM preprocessor

How should the computation step be configured?
![image](https://user-images.githubusercontent.com/7193853/219773872-5730b8a7-77bb-432f-bc03-1aca2b33ad12.png)

Is this the right mapping?
![image](https://user-images.githubusercontent.com/7193853/219774119-d42daa7a-3e85-4792-b591-7cca471c13fc.png)

**Comment by dylanmartin** [comment]
There are 2 issues here:
1. The download failed for some reason
2. It appears that the file exists and therefor passes the `isSingularityImageLatest` check but the image is bad
![image](https://user-images.githubusercontent.com/7193853/219778590-e1d21775-0526-43e0-90a9-42fafff610b2.png)

![image](https://user-images.githubusercontent.com/7193853/219778655-00eb692c-0fb4-468e-b949-dcbfc9186c52.png)

**Comment by dylanmartin** [comment]
`rm -rf` the image gets permission denied
![image](https://user-images.githubusercontent.com/7193853/219780198-1e490d74-f4ef-477f-ad45-46367ff33f99.png)
sudo works

**Comment by dylanmartin** [comment]
It looks like permission is denied to add the files when downloading


![Image](https://user-images.githubusercontent.com/7193853/219783618-26b3573a-fb9f-4da3-aef3-8ca84a021325.png)

**Comment by dylanmartin** [comment]
Adding the `--fix-perms` option so `singularity build` was a suggested solution in the error text.
That seemed to potentially fix the problem but now there's an error saying 'not enough space on device'
I'll clear some space to see if it works. 
There is a warning in the error text that says: `WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container.`
Let's revisit to make sure it isn't a security issue.

**Comment by dylanmartin** [comment]
We may need more space on this volume
![image](https://user-images.githubusercontent.com/7193853/219790615-d1c58d27-c7fe-477f-9efb-979d45620c1a.png)

**Comment by dylanmartin** [comment]
Increased size of storage on the EC2 instance from 30GB to 60GB. No longer running int device space limits.

**Comment by dylanmartin** [comment]
Running VBM pre
![image](https://user-images.githubusercontent.com/7193853/220419668-d2ea0107-3594-4219-818d-7d8e21f5e443.png)

**Comment by dylanmartin** [comment]
It looks like the docker image for the remote isn't pulled
![image](https://user-images.githubusercontent.com/7193853/220436731-0276911b-82e2-460a-8d6b-dd870a59830c.png)

**Comment by dylanmartin** [comment]
![image](https://user-images.githubusercontent.com/7193853/220438649-2b72380c-b20e-4841-9895-5a30acde3bc4.png)

**Comment by dylanmartin** [comment]
Computation is running
![image](https://user-images.githubusercontent.com/7193853/220438799-d7f88daf-d452-404b-ad2d-a35a1db81dc2.png)

**Comment by dylanmartin** [comment]
![image](https://user-images.githubusercontent.com/7193853/220438902-92ce2264-ae0a-4c36-8d39-e51503d17ff0.png)

![image](https://user-images.githubusercontent.com/7193853/220438989-9552fc77-62c5-4a6b-804e-1b519998f37a.png)
Is this the expected result from VBM pre?

**Comment by dylanmartin** [comment]
@rssk which of these computations is "VBM regression"?
![image](https://user-images.githubusercontent.com/7193853/220439588-dafccfe7-806e-4a6d-b991-1cb433bc0929.png)
I'm guessing it's Regression - VBM

**Comment by dylanmartin** [comment]
Configuring the VBM regression pipeline step this way:
![image](https://user-images.githubusercontent.com/7193853/220439941-f6a44f44-a159-413f-a9e2-88cc14ad7006.png)

**Comment by dylanmartin** [comment]
Files are showing up in the wrong place
![image](https://user-images.githubusercontent.com/7193853/220470009-314bebd6-f104-497e-bbac-f505f7a448e1.png)

**Comment by dylanmartin** [comment]
VBM preprocessor is taking a while. Moving on to VBM regression to see if that completes. Using this configuration:
![image](https://user-images.githubusercontent.com/7193853/220754101-594ce045-e16c-44e8-a49f-120edabad856.png)
![image](https://user-images.githubusercontent.com/7193853/220754190-ecc19d6f-94c3-4f80-b919-cddc98ca8dc0.png)

**Comment by dylanmartin** [comment]
![image](https://user-images.githubusercontent.com/7193853/220757614-4cd3a348-498f-4c8e-86e5-bb4edf45ea1d.png)

**Comment by dylanmartin** [comment]
![image](https://user-images.githubusercontent.com/7193853/220783052-e177accc-8949-4534-95d6-50c5de7c89ea.png)

**Comment by dylanmartin** [comment]
It isn't necessarily true that these runs are hanging because we're using Singularity. It's likely there is some other issue.

**Comment by dylanmartin** [comment]
https://github.com/trendscenter/coinstac/issues/1693

**Comment by dylanmartin** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/7193853/222759497-4adb9252-4baf-4dd2-9cb6-38c5078607fa.png">

**Comment by dylanmartin** [comment]
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/7193853/222763404-432812a1-f0cf-4fcc-950b-06fe816f159d.png">

Line 79 in the startscript is `exec $@`. To see the contents of `$@`, the values can be echoed and sent to the logs. The container must be rebuilt from this container recipe to run the modified startscript.

**Comment by dylanmartin** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/7193853/222788420-1331c557-b974-4af5-ba0a-8301d0988896.png">
Modify runscript and not startscript

**Comment by dylanmartin** [comment]
Echo successfully logged. It looks like a json object is being passed into the exec command. Are these the expected arguments?
<img width="908" alt="image" src="https://user-images.githubusercontent.com/7193853/222789218-72730a5f-993b-466d-874c-b82b70de4469.png">

**Comment by dylanmartin** [comment]
Are these the correct args?
<img width="911" alt="image" src="https://user-images.githubusercontent.com/7193853/222790178-81a0e380-a50f-4e74-b7ff-0d30210c53b8.png">

**Comment by dylanmartin** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/7193853/222792457-56a583cc-e3dd-42e9-a82e-392bb0572266.png">

**Comment by dylanmartin** [comment]
ServiceFunctionGenerator is not getting a compspecVersion argument so it defaults to 1.
the `opts` parameter to createService does contain a key called `version` that appears to reflect the compspec version.

**Comment by dylanmartin** [comment]
After feeding the correct compspecVersion to serviceFunctionGenerator, the code goes down compspecVersion 2 switch case. it then encounters this error
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/7193853/222816063-a1eaa058-ac7b-40c1-ad3f-4eea77bafcbd.png">
The error executing the `exec` function in the startscript happens as well.

**Comment by dylanmartin** [comment]
This is what gets passed to spawn when starting the container
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/7193853/222829048-d00d3f74-9c15-4aeb-be3c-55864b608f7b.png">

**Comment by dylanmartin** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/7193853/222830910-a0888c14-4d24-4879-82e6-ff00e3d87760.png">

Are these the commands that need to be executed by the `exec` line in the runscript?

**Comment by rssk** [comment]
- [ ] ssr regression, compspec type 2
  https://github.com/trendscenter/coinstac-regression-fsl
- [ ] vbm preprocessor, compspec type 1
  https://github.com/trendscenter/Coinstac_VBM_computation
- [ ] vbm regression, compspec type 2
  https://github.com/trendscenter/coinstac-regression-vbm
- [ ] decentralized mancova, compspec type 1
  https://github.com/trendscenter/coinstac-mancova/tree/master/coinstac_mancova

**Comment by dylanmartin** [comment]
We must not be running from the .sif

**Comment by dylanmartin** [comment]
ws error not bubbling up
![image](https://user-images.githubusercontent.com/7193853/223570307-3ed33b7c-69b1-49a6-8d08-6dfbab2225b3.png)

**Comment by dylanmartin** [comment]
The python server inside the singularity container for compspecVersion 2 needs to know what port to listen on for ws connections.

**Comment by rssk** [comment]
Investigate if a non zero exit code process triggers singularity instance to propagate or other show the error

* what happens when a container cannot be immediately started? (errors on startup)
  -- _needs more testing_
  -- immediately crashing containers leave logs, but no other events?
  -- fixed this? for whatever reason singularity has its stderr and stdout streams swapped
      leading to the error output being missed, reversed these and seems fine for now. Asked the singularity devs whats up
* what happens when a container exits randomly?
    -- needs more testing
* what happens when a pipeline computation internally fails and throws?
  -- exits to the UI as expected 👍

**Comment by dylanmartin** [comment]
The above comment is referring to the entry command script. For example:
```
    "command": [
      "python",
      "\/computation\/scripts\/local.py"
    ],
```

**Comment by rssk** [comment]
Got vbm working, had to fix the passed in env to singularity's start, they need to be comma separated ` --env B=1,C=1`
