### ISSUE TITLE
Improve Algorithm Simulator API

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#23]
As per the Albuquerque meeting on 2016-08-15 and 2016-08-16 and the discussion with Sergey on 2016-08-17, we need to improve _coinstac-simulator_ so that algorithm authors can start using it.

_coinstac-simulator_ already functions as an executable, and Sergey already has it installed globally. Great! I think this method provides the least setup friction for authors. Sergey has a _declaration.js_ file that contains an object that _coinstac-simulator_ consumes. It looks approximately like:

``` js
const n = require('numeric');

module.exports = {
  user1: {
    name: 'user 1',
    data: n.transpose([
      [0.001, 0.002, 0.003],
      // Lots of data here...
    ]),
  },
  user2: {
    name: 'user 2',
    data: n.transpose([
      // More data!
    ]),
  },
  user3: {
    name: 'user 3',
    data: n.transpose([
      // Tons of arrays!
    ]),
  },
  server: {
    // Some opts for remote
  },
};
```

Sergey doesn’t want to continually copy-paste numbers into his _declaration.js_ file.

Here’s a CLI suggestion:

``` shell
coinstac-simulator --declaration declaration.js \
  --user1 path/to/files1/**/*.txt \
  --user2 path/to/files2/**/*.txt \
  --user3 path/to/files3/**/*.txt
```

This would use *NIX globbing to pass target files to the declaration, which would then run. However, this doesn’t allow for user configuration or server vars. Another take:

``` js
const cstacSimulator = require('coinstac-simulator');

module.exports = {
  user1: {
    x: cstacSimulator.loadFiles('./data/**/*.txt'),
    y: cstacSimulator.loadFile('./data/path/my-file.txt'),
    z: 3e-3,
    aa: [0.011, 0.015, 0.513, 0.744],
  },
  user2: {
    // ...
  },
};
```

If we export utilities for file loading on on _coinstac-simulator_ it could help authors out. Alternatively:
- We tell them to learn Node.js. Might be too steep a learning curve
- We give code examples in some sort of documentation that shows how to load files. Something like:
  
  ``` js
  // Here's how to get some files into your program!
  const fs = require('fs');
  const glob = require('glob'); // External package for *NIX-like globbing
  const path = require('path'); // Built-in used to resolve paths
  
  // `files` is an array of full file paths
  const files = glob.sync(path.join(__dirname, 'my/data/**/*.txt'));
  
  // `filesMap` contains filenames in the keys and corresponding file contents
  // in values
  const filesMap = new Map(files.map(f => {
    return [file, fs.readFileSync(file)];
  }));
  ```
  
  Is this confusing? Should we be teaching algo developers Node.js? _(Uhg, sync.)_

**Todos:**
- [x] Run parameters: authors should be able to specify run-specific parameters. The starting client sets up the run, so it makes sense for these run params to be passed through it. Also, consider the case where a user's local params are different remote params.
- [x] Determine whether authors need Node.js help or _coinstac-simulator_ utils. Implement utils if necessary.
- [x] Write documentation (“how to” guide?) for algorithm authors.

**Comment by cdaringe** [comment]
Oh good ideas!  There's already a how-to, but it needs some more work.
It's currently called DECENTRALIZED_XYZ.md.  I think the sim readme refs it

**Comment by swashcap** [comment]
We’re considering changing the object shape for a simulator declaration (_declaration.js_ in Sergey’s examples). Right now it looks like this:

``` js
const path = require('path');

module.exports = {
  users: [{
    username: 'user1',
    userData: [
      // Data here...
    ],
  }, {
    username: 'user2',
    userData: [
      // Data here...
    ],
  }],
  computationPath: path.resolve(
    __dirname,
    'path/to/decentralized-computation.js'
  ),
  verbose: true,
};
```

We’re considering changing this structure to make algorithm development easier for authors. Proposition for declarations:

``` js
module.exports = {
  computationPath: './relative/path/to/computation.js',
  local: [{
    x: [/* ... */],
    y: [/* ... */],
  }, {
    x: [/* ... */],
    y: [/* ... */],
  }, {
    // And so on...
  }],
  remote: {
    // Remote variables/config here
  },
};
```

Key changes:
- Change `computationPath` to not rely on path resolution. _coinstac-simulator_ can own this complexity.
- Change `users` to `local` and `server` (not shown above) to `remote`. This makes the declaration structure mirror the decentralized computation structure, which should make _coinstac-simulator_ use easier for authors.
- `local` no longer has objects with `username` and `userData`. This strategy works well for small data sets, but it seems tedious for large collections of files or programmitic use. Instead, the `local` array contains objects which will become “local” runners, or clients. These objects may contain arbitrary data; _coinstac-simulator_ can generate usernames and the necessary client setup.

In addition to object changes, we expect algorithm authors to have sets of files stored meaningfully in directories. Instead of teaching authors to use Node.js to read the files' contents, we will provide utilities:

#### **`loadFiles(pattern, filter)`**: load files' contents into a declaration
- _`pattern`_ (string): File path globbing pattern
- _`filter`_ (Function): File filterer

##### Use

This assumes files important to an algorithm are stored in a directory:

``` shell
$ tree .
└── mydir
    ├── file-1.txt
    ├── file-2.txt
    ├── file-3.txt
    └── mysubdir
        └── file-4.txt
```

``` js
const coinstacSimulator = require('coinstac-simulator');

module.exports = {
  computationPath: './relative/path/to/computation.js',
  local: [{
    // Load all the txt files using globbing:
    x: coinstacSimulator.loadFiles('./path/to/files/**/*.txt'),

    // Can still use plain values:
    y: [3.03, 4.07, 1.06],
  }, {
    // Load all files, then filter by files starting with 'M':
    x: coinstacSimulator.loadFiles(
      './pick/some/files/**/*',
      file => file.charAt(0) === 'M'
    ),
    y: [6.43, 7.01, 9.15],
  }],
  remote: {
    // ...
  },
};
```

#### **`loadDir(path, filter, mapToVars)`**: load a directory's contents
- _`path`_ (string): File path to directory
- _`filter`_ (Function): File filterer
- _`mapToVars`_ (Function): Maps file contents to variables

##### Use

This expects the specified path to contain a subdirectories that coorespond to separate clients. Consider:

``` shell
$ tree path/to/files
├── set-1
│   └── x
│   │   ├── file-1.txt
│   │   ├── file-2.txt
│   │   └── file-3.txt
│   └── y
│       ├── file-4.txt
│       ├── file-5.txt
│       └── file-6.txt
├── set-2
│   └── x
│   │   ├── file-7.txt
│   │   ├── file-8.txt
│   │   └── file-9.txt
│   └── y
│       ├── file-10.txt
│       ├── file-11.txt
│       └── file-12.txt
└── set-3
    └── x
    │   ├── file-13.txt
    │   ├── file-14.txt
    │   └── file-15.txt
    └── y
        ├── file-16.txt
        ├── file-17.txt
        └── file-18.txt
```

There are three local “clients” in this case: _set-1_, _set-2_, and _set-3_. Each subdirectory’s _subdirectory_ becomes a variable.

``` js
const coinstacSimulator = require('coinstac-simulator');

module.exports = {
  computationPath: './relative/path/to/computation.js',

  // Load the entire directory
  local: coinstacSimulator.loadDir('./path/to/files'),
  remote: {
    // ...
  },
};
```

@pliz @adsarwate What are your thoughts on these changes? Will they meet computation authors’ needs?

**Comment by cdaringe** [comment]
- not sure how simulator can own the complexity of finding the
  DecentralizedComputation.  Simulators job is in fact to take a DComp as
  input and simulate it.  Thus, not providing a DComp as input doesn't make
  sense.  If using the cli, then it could of course assume cwd for where to
  find the DComp, but even that is a can of worms
- the local/remote strategy will break group step.  Group step relies on
  making sure all users gave contributed at each iteration.  You can stub a
  dummy one in, of course, but calls to triggerRunner expect a well formed
  Local ComputationResult.  Just FYI, you'll find this in the process.
- the scale factor argument doesn't really make sense or add up, IMHO, but
  I get that it's one more layer in the object/are structure
- the loadFiles API is a great idea for some sugar to help authors.  Nice.
  I'm going to speak on behalf of @pliz and say "I love it!", just give me a
  concise cheat sheet to reference

**Comment by adsarwate** [comment]
Sorry I need to parse this all tomorrow AM. Examples that the structure should accommodate:

1) Each site gets a matrix, possibly of different sizes at each site.
2) Each site gets a list of strings containing URLs
3) Some sites get matrices and other sites get strings.
4) Each site gets one of the above and different subroutine (or the function pointer) that it gets to run

I think that’s how the spec works below but let me know if some of these cases are not covered: I don’t think the (x,y) distinction is something you want to hard-code into the simulator since it’s only relevant for certain methods.

**Comment by sergeyplis** [comment]
I believe x and y are not hard coded. This is up to the algorithm developer to decide what to name the data variables. May be easier to think of it as a data dictionary. So for your matrices example @adsarwate, the coinstac-simulator user developing the algorithm could call `M: loadFiles()`. Also the examples with tree, I believe are hypothetical. Since `loadDir` function takes another function `maptoVars` that implies one can use their existing directory structure if it is conceptually organized as the data are expected to enter the algorithm.

**Comment by swashcap** [comment]
> not sure how simulator can own the complexity of finding the DecentralizedComputation

Simulator can do the work of resolving the decentralized definition path based on _declaration.js_’s current working directory. This should be pretty easy:

``` js
const path = require('path');
const declaration = require('./dynamic/path/to/declaration.js');

const compFullPath = path.resolve(
  require.resolve(declaration),
  declaration.computationPath
);
```

> the local/remote strategy will break group step.

Good to know. It’s best to provide authors an easy-to-use format and deal with complexity inside _coinstac-simulator_. It shouldn’t be hard to map the newly proposed object into something _coinstac-common_ can use.

> the scale factor argument doesn't really make sense or add up

Totally lost here. What’s the “scale factor argument?”

_(Just added `computationPath` to each declaration for clarity.)_

**Comment by swashcap** [comment]
> Each site gets a matrix, possibly of different sizes at each site.

This format should support this. Items in the `local` array equate to a site’s (or, client’s) data.

> Each site gets a list of strings containing URLs

_Interesting._ Should _coinstac-simulator_ pull down data from the URL and use it for the simulation?

> Each site gets one of the above and different subroutine (or the function pointer) that it gets to run

_Double interesting._ You’d like to be able to select a site’s algorithm? What’s the use case for this?

> I don’t think the (x,y) distinction is something you want to hard-code into the simulator

Right: those are example properties. Authors will be able to shape their data as they see fit, and _coinstac-simulator_ should just toss it into the algorithm.

**Comment by swashcap** [comment]
> Since `loadDir` function takes another function `maptoVars` that implies one can use their existing directory structure if it is conceptually organized as the data are expected to enter the algorithm.

Right. Is it reasonable to assume data is already organized in directories? We can hopefully leverage this to make _coinstac-simulator_ simpler.

**Comment by adsarwate** [comment]
> Each site gets a list of strings containing URLs
> 
> Interesting. Should coinstac-simulator pull down data from the URL and use it for the simulation?

Nah, but maybe the local instances would want to do this themselves (if they have access). For example: NIH stores reference genomes on their server. You might want each site as part of an initialization to download a particular genome and do some preprocessing on it.

> Each site gets one of the above and different subroutine (or the function pointer) that it gets to run
> 
> Double interesting. You’d like to be able to select a site’s algorithm? What’s the use case for this?

Maybe you’re testing out a procedure wherein sites randomly select themselves to do function A or function B. I don’t have a specific example in mind, but was just trying to throw out scenarios which maybe could happen to make sure the simulator isn’t too constrained.

Anand

**Comment by swashcap** [comment]
@adsarwate Thanks for the feedback. Downloadable data is a great idea, but probably not necessary to make these simulator API improvements. As far as randomly selected functions, we’re working on dynamic declarations in #26. I imagine authors will code up their scripts for this themselves, and the simulator will simply consume the command-type computations.

We’re going to implement the `loadFile` and `loadDir` utilities. We can easily extend/modify the API further if needed. :smile:

**Comment by swashcap** [comment]
#33 addresses this. If you have any feature requests, bug reports or quetsions please open an issue!
